  GNU nano 4.8                                           filebeat-playbook.yml
---
- name: installing and launching filebeat
  hosts: TODO
  become: yes
  tasks:

  - name: download filebeat deb
    command: curl -L -O https://artifacts.elastic.co/downloads/beats/filebeat/filebeat-7.4.0-amd64.deb

  - name: install filebeat deb
    command: dpkg -i filebeat-7.4.0-amd64.deb

  - name: drop in filebeat.yml
    copy:
      src: /etc/ansible/files/filebeat-config.yml
      dest: TODO

  - name: enable and configure system module
    command: TODO

  - name: setup filebeat
    command: TODO

  - name: start filebeat service
    command: TODO

  - name: enable service filebeat on boot
    systemd:
      name: TODO
      enabled: yes


